config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  namespace :admin do
    get 'questions/index'
    get 'users/index'
    resources :users, only: %i[index destroy]
    resources :questions, only: %i[index destroy]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  root to: 'questions#index'
  get 'questions/unsolved'
  get 'questions/solved'
  resources :questions
  resources :questions do
    resources :answers, only: %i[create destroy]
    resource  :solve, only: [:create], to: 'questions#solve'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :detail, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :detail, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :questions
  has_many :answers
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  layout 'admin_header'
  def index
    @questions = Question.all
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy!
    redirect_to admin_questions_index_path, notice: "「#{question.title}」を削除しました", status: :see_other
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin_header'

  def index
    @users = User.all
  end

  def destroy
    user = User.find(params[:id])
    user.destroy!
    redirect_to admin_users_index_url, notice: "「#{user.name}」を削除しました", status: :see_other
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.create!(detail: answer_params[:detail], question_id: params[:question_id], user_id: current_user.id)
    redirect_to question_url(params[:question_id]), notice: "回答を追加しました"
    AnswerMailer.creation_email(@answer, current_user).deliver_now
  end

  def destroy
    Answer.find(params[:question_id]).destroy!
    redirect_to question_url(params[:question_id]), notice: "回答を削除しました"
  end

  private
  def answer_params
    params.require(:answer).permit(:detail, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :login_required, only: [:index, :solved, :unsolved, :show]
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page])
  end
  def solve
    question = Question.find(params[:question_id])
    question.update!(status: 1)
    redirect_to questions_url, notice: "質問 #{question.title}を解決済みにしました。"
  end

  def unsolved
    @q = Question.where(status: 0).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page])
  end

  def solved
    @q = Question.where(status: 1).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user&.id
    @question.save!
    QuestionMailer.creation_email(@question, current_user).deliver_now
    redirect_to questions_url, notice: "質問 #{@question.title}を登録しました。"
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: @question.id)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    question = current_user.questions.find(params[:id])
    question.update!(question_params)
    redirect_to questions_url, notice: "質問「#{question.title}」を更新しました"
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: "質問「#{question.title}」を削除しました", status: :see_other
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      if user.admin == true
        redirect_to admin_questions_index_url notice: '管理者としてログインしました'
      else
        redirect_to root_url, notice: 'ログインしました'
      end
    else
      render :new
    end
  end

  def destroy
    redirect_to root_url, notice: 'ログアウトしました'
    reset_session
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url(@user), notice: "#{@user.name}を登録しました"
    else
      render :new
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/application.html.slim
doctype html
html
  head
    title
      | QA
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand

      u1.navbar-nav.ml-auto
        li.nav-item= link_to 'questionaaaaa', questions_path, class: 'nav-link'
        -if current_user
          li.nav-item= link_to  'logout', logout_path, data: { turbo_method: :delete } ,class: 'nav-link'
          li.nav-item= link_to  'user一覧', users_path ,class: 'nav-link'
          li.nav-item.disabled = current_user.name
          item =  image_tag current_user.image.variant(:thumb)   if current_user.image.attached?
        -else
          li.nav-item= link_to 'login', login_path,class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice

    = yield

app/views/admin/questions/index.html.slim
h1 管理者用QA一覧

.mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th = "title"
        th = "name"
      tbody
        -   @questions.each do |question|
          tr
            td = question.title
            td = question.user.name
            td = link_to  '削除', [:admin, question], data: { turbo_method: :delete,turbo_confirm: "#{question.title}を削除しますか？"} ,class: 'btn btn-danger'

app/views/admin/users/index.html.slim
h1 管理者用ユーザ一覧

.mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th = "name"
      tbody
        - @users.each do |user|
          tr
            td = image_tag user.image.variant(:thumb),class:"user-icon"   if user.image.attached?
            td = user.name
            td = user.admin
            td = link_to  '削除', [:admin, user], data: { turbo_method: :delete,turbo_confirm: "#{user.name}を削除しますか？"} ,class: 'btn btn-danger'

app/views/layouts/admin_header.html.slim
doctype html
html
  head
    title
      | QA
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand

      u1.navbar-nav.ml-auto
        li.nav-item= link_to 'question', admin_questions_index_path, class: 'nav-link'
        -if current_user
          li.nav-item= link_to  'logout', logout_path, data: { turbo_method: :delete } ,class: 'nav-link'
          li.nav-item= link_to  'user一覧', admin_users_path ,class: 'nav-link'
          li.nav-item.disabled = current_user.name
          item =  image_tag current_user.image.variant(:thumb)   if current_user.image.attached?
        -else
          li.nav-item= link_to 'login', login_path,class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice

    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QA
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand

      u1.navbar-nav.ml-auto
        li.nav-item= link_to 'question', questions_path, class: 'nav-link'
        -if current_user
          p =  current_user.name
          li.nav-item= link_to  'logout', logout_path, data: { turbo_method: :delete } ,class: 'nav-link'
          li.nav-item= link_to  'user一覧', users_path ,class: 'nav-link'
        -else
          li.nav-item= link_to 'login', login_path,class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice

    p = current_user
    = yield

app/views/questions/_form.html.slim
= form_with model: question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control' ,id: 'question_title', required: true
  .form-group
    = f.label :detail
    = f.text_area :detail, rows: 5, class: 'form-control', id: 'question_detail', required: true
  = f.submit nil, class: 'btn btn-primary'

app/views/questions/_question.html.slim
.mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th = "名称"
        th = "作成時刻"
      tbody

        - @questions.each do |question|
          tr
            td = link_to question.title, question_path(question)
            td = question.created_at
            td
              = link_to '編集', edit_question_path(question) , class: 'btn btn-primary mr-3'
              = link_to '削除', question, data: { turbo_method: :delete, turbo_confirm: "#{question.title}を削除しますか？" }, class: 'btn btn-danger'
  = paginate @questions
  = page_entries_info @questions

app/views/questions/_questionindexshow.html.slim
.mb-3
  table.table.table-hover
    thead.thead-default
      - @questions.each do |question|
        li.media.mb-3.border-bottom.pb-3
          img.mr-3.rounded-circle = image_tag question.user.image.variant(:thumb)
          .mr-3
          - if question.status == 0
            badge.badge-danger 未解決
          - else question.status == 1
            badge.badge-danger 解決済

          .media-body
            .d-flex
              h5.mt-0.mb-1.mr-3
                = link_to question.title, question_path(question)
            = question.detail

app/views/questions/edit.html.slim
h1 編集画面

.nav.justify-content-end
  = link_to '一覧', questions_path, class: 'nav-link'

= render partial: 'form', locals: { question: @question}

app/views/questions/index.html.slim
= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :title_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'
= link_to '新規作成', new_question_path, class: 'btn btn-primary'

ul.nav.nav-tabs
  li.nav-item
    a.nav-link.active aria-current="page" href= questions_path  全て
    = render partial: 'questionindexshow', locals: { questions: @questions}
  li.nav-item
    a.nav-link href=questions_solved_path  解決済み
  li.nav-item
    a.nav-link href=questions_unsolved_path  未解決

app/views/questions/new.html.slim
h1 質問投稿

.nav.justify-content-end
  = link_to '一覧', questions_path, class: 'nav-link'

= render partial: 'form', locals: { question: @question}

app/views/questions/show.html.slim
h1 詳細

.nav.justify-content-end
  - if @question.status == 0
    badge.badge-danger 未解決
    - if current_user&.id == @question.user_id
      = button_to '解決済にする', question_solve_path(@question), data: { turbo_method: :post,turbo_confirm: "#{@question.title}を解決済みにしますか？"}, class: 'nav-link'
  - else @question.status == 1
    badge.badge-danger 解決済

.nav.justify-content-end
  = link_to '一覧へ戻る', questions_path,  class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= '質問者'
      th = User.find(@question.user_id).name if @question.user_id
    tr
      th = 'title'
      th =  @question.title
    tr
      th = 'detail'
      th = simple_format(h(@question.detail),{},sanitize: false, wrapper_tag: "div")
    tr
      th = '作成時刻'
      th = @question.created_at
- if current_user&.id ==@question.user_id
  = link_to '編集', edit_question_path, class: 'btn btn-primary mr-3'
  = button_to '削除', @question, method: :delete, data: { turbo: false }
  / = link_to '削除', @question, data: { turbo_method: :delete,turbo_confirm: "#{@question.title}を削除しますか？"} ,class: 'btn btn-danger'


.card.card-body
  = form_with model:[@answers],url: question_answers_path(@question.id), method: :post,local: true do |f|
    .form-group
      = f.label '回答する'
      = f.text_field :detail, class: 'form-control', required: true
    = f.submit '送信', class: 'btn btn-primary'

  ul.list-unstyled
    ul.list-unstyled
     - @answers.each do |answer|
        li.media.mb-3.border-bottom.pb-3
          img.mr-3.rounded-circle = image_tag answer.user.image.variant(:thumb)
          .media-body
            .d-flex.flex-column.justify-content-between
            div
             p =answer.detail
            .text-right
              div
                - if current_user&.id == answer.user_id
                  = link_to '削除', question_answer_path(answer), data: { turbo_method: :delete,turbo_confirm: "削除しますか？"} ,class: 'btn btn-danger'
              span.small.text-muted = answer.created_at

app/views/questions/solved.html.slim
= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :title_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'
= link_to '新規作成', new_question_path, class: 'btn btn-primary'

ul.nav.nav-tabs
  li.nav-item
    a.nav-link href= questions_path  全て
    = render partial: 'questionindexshow', locals: { questions: @questions}
  li.nav-item
    a.nav-link.active aria-current="page" href=questions_solved_path  解決済み
  li.nav-item
    a.nav-link href=questions_unsolved_path  未解決

app/views/questions/unsolved.html.slim
= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :title_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'
= link_to '新規作成', new_question_path, class: 'btn btn-primary'

ul.nav.nav-tabs

  li.nav-item
    a.nav-link href= questions_path  全て
    = render partial: 'questionindexshow', locals: { questions: @questions}
  li.nav-item
    a.nav-link href=questions_solved_path  解決済み
  li.nav-item
    a.nav-link.active aria-current="page" href=questions_unsolved_path  未解決

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/index.html.slim
h1 ユーザ一覧

.mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th = "img"
        th = "name"
      tbody
        - @users.each do |user|
          tr
            td = image_tag user.image.variant(:thumb),class:"user-icon"   if user.image.attached?
            td = user.name
            td

app/views/users/new.html.slim
h1 ユーザ登録

= form_with model: [@user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label :email, 'メールアドレス'
    = f.email_field :email, class: 'form-control', required: true
  .form-group
    = f.label :password, 'password'
    = f.password_field :password,class:'form-control', required: true

  .form-group
    = f.label :password_confirmation, 'password(確認)'
    = f.password_field :password_confirmation,  class: 'form-control', required: true
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'

  = f.submit '登録', class: 'btn btn-primary'